#!/bin/bash

JAILS="`fail2ban-client status | grep 'Jail list' | sed -E 's/^[^:]+:[ \t]+//' | sed 's/,//g'`"
for JAIL in ${JAILS}
do
  fail2ban-client status "${JAIL}"
  echo
  iptables -nv -L "f2b-${JAIL}" | grep -v RETURN
  echo
  echo
done

