#!/bin/bash

DOCPATH="$1"
DOCTYPE="$2"
NALTYPE="$3"
NALHGHT="${4:-600}"

[ "$1" = "" -o "$2" = "" -o "$3" = "" ] && {
  echo "fixthumbs <Document root> <Document type/file extension> <Thumbnail type/file extension> <Nail height in px, 600 default>"
  exit
  }


[ -d "${DOCPATH}" ] || {
  echo "no directory at >${DOCPATH}<"
  exit
  }

TEMPDIR="/tmp"

for TYPE in "${DOCTYPE}" "${NALTYPE}" ; do
  find "${DOCPATH}" -name "*.${TYPE}" | sed 's%^\(.*\)....$%\1%g' | sort -u > "${TEMPDIR}/${TYPE}.txt"
  done


find "${DOCPATH}" -name "*.${DOCTYPE}" | sort -u > "${TEMPDIR}/${DOCTYPE}.txt"
SEDSTR="s%^\(.*/\)\(.*\)\.${DOCTYPE}\$%\1th_\2%g"
cat  "${TEMPDIR}/${DOCTYPE}.txt" | sed "${SEDSTR}" | sort -u > "${TEMPDIR}/projected.txt"

SEDSTR="s%^\(.*\)\.${NALTYPE}\$%\1%g"
find "${DOCPATH}" -name "*.${NALTYPE}" | sed "${SEDSTR}" | sort -u > "${TEMPDIR}/${NALTYPE}.txt"

comm -23 "${TEMPDIR}/projected.txt" "${TEMPDIR}/${NALTYPE}.txt" | sed 's%^\(.*\)/th_\(.*\)$%\1/\2%g' > "${TEMPDIR}/lonely${DOCTYPE}.txt"
comm -13 "${TEMPDIR}/projected.txt" "${TEMPDIR}/${NALTYPE}.txt" > "${TEMPDIR}/lonely${NALTYPE}.txt"

#rm "${TEMPDIR}/${DOCTYPE}.txt"
#rm "${TEMPDIR}/${NALTYPE}.txt"
#rm "${TEMPDIR}/projected.txt"

NRPNG="`cat "${TEMPDIR}/lonely${NALTYPE}.txt" | wc -l`"
echo "Found ${NRPNG} thumbnails without matching document."
for FILE in `cat "${TEMPDIR}/lonely${NALTYPE}.txt"`; do
  echo "Removing lonely ${FILE}.${NALTYPE}"
  rm "${FILE}.${NALTYPE}"
  done
#rm "${TEMPDIR}/lonely${NALTYPE}.txt"


NRPDF="`cat "${TEMPDIR}/lonely${DOCTYPE}.txt" | wc -l`"
echo "Found ${NRPDF} documents without matching thumbnail."
for FILE in `cat "${TEMPDIR}/lonely${DOCTYPE}.txt"`; do
  THUMB="`echo ${FILE} | sed 's%^\(.*/\)\(.*\)$%\1th_\2%g'`"
  echo "Creating thumbnail for ${FILE}.${DOCTYPE}"
  convert -thumbnail "x${NALHGHT}" "${FILE}.${DOCTYPE}[0]" "${THUMB}.${NALTYPE}"
  done
#rm "${TEMPDIR}/lonely${DOCTYPE}.txt"

