#!/usr/bin/python

import urllib2

baseURL='dev.gawati.org'

packages=[
{'name': 'gawati-portal-ui', 'URLprefix': '', 'URLpath': ''},
{'name': 'gawati-client', 'URLprefix': 'data.', 'URLpath': ''},
{'name': 'gawati-data', 'URLprefix': 'data.', 'URLpath': '/gwd'},
{'name': 'gawati-portal-server', 'URLprefix': 'data.', 'URLpath': '/gwp'},
{'name': 'gawati-user-profiles', 'URLprefix': 'data.', 'URLpath': '/gwu'},
{'name': 'gawati-client-data', 'URLprefix': 'data.', 'URLpath': '/gwdc'},
{'name': 'gawati-client-server', 'URLprefix': 'data.', 'URLpath': '/gwc'},
]

services=[]

for package in packages:
  service = {}

  try:
    reply = urllib2.urlopen("https://" + package['URLprefix'] + baseURL + package['URLpath'] + "/about").read()
    reply = reply.split(';')

    for data in reply:
      key,value = data.split('=')
      service[key] = value

    services.append([package,service])

  except:
    services.append([package,{'package':'','version':'-'}])

for service in services:
  if (service[0]['name'] == service[1]['package']):
    print(service[0]['name'] + ' available. Reported version: ' + service[1]['version'])

  else:
    print(service[0]['name'] + ' not available at ' + "https://" + service[0]['URLprefix'] + baseURL + service[0]['URLpath'])

